### ISSUE TITLE
Add optional comment from submitter

### ISSUE THREAD

**Issue by pietroppeter** [nathancoleman/musicleague#150]
It would be nice if, when submitting a song, you could post a comment that will be revealed at the end of the round. The comment can be used e.g. to explain why you are making this specific submission.

**Comment by nathancoleman** [comment]
Hi @pietroppeter! This is a feature that I'm nearly finished with! However, it will, at least initially, be limited to the financial backers keeping the lights on over on [Patreon](https://patreon.com/musicleague).

**Comment by nathancoleman** [comment]
This functionality was just merged in #153

**Comment by pietroppeter** [comment]
hi @nathancoleman! That's very nice! I did not know there was a Patreon for this, I guess I finally have a great opportunity to start using patreon!

You might want to advertise a bit more your patreon, I cannot find any mention of it in github repo (there is no [sponsor section](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) and no mention of it in the readme). Also the main site does not mention it (hey it does not even have a link to the github repo, but maybe that is intentional...).
